"use client";

import { useActionState } from "react";

import { adjustStock, stockIn, type InventoryActionState } from "./actions";

const initialState: InventoryActionState = {};

export function InventoryActions({ products }: { products: { id: string; name: string; product_code: string }[] }) {
  const [stockState, stockAction, stockPending] = useActionState(stockIn, initialState);
  const [adjustState, adjustAction, adjustPending] = useActionState(adjustStock, initialState);
  return <div className="mb-6 grid gap-6 xl:grid-cols-2">
    <form action={stockAction} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold text-slate-950">Stock in</h2><p className="mt-1 text-sm text-slate-500">Record a delivery and update the current cost.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><select name="productId" required className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm sm:col-span-2">{products.map((product) => <option key={product.id} value={product.id}>{product.product_code} · {product.name}</option>)}</select><input name="receiptDate" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm" /><input name="quantity" type="number" min="1" required placeholder="Quantity" className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm" /><input name="unitCost" type="number" min="0" step="0.01" required placeholder="Unit cost" className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm" /><input name="supplierName" placeholder="Supplier (optional)" className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm" /></div>{stockState.error ? <p role="alert" className="mt-4 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{stockState.error}</p> : null}{stockState.success ? <p role="status" className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{stockState.success}</p> : null}<button type="submit" disabled={stockPending} className="mt-5 h-11 w-full rounded-xl bg-blue-700 text-sm font-semibold text-white hover:bg-blue-800 disabled:bg-slate-300">{stockPending ? "Saving…" : "Save stock-in"}</button></form>
    <form action={adjustAction} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold text-slate-950">Stock adjustment</h2><p className="mt-1 text-sm text-slate-500">Every adjustment requires a reason and audit entry.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><select name="productId" required className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm sm:col-span-2">{products.map((product) => <option key={product.id} value={product.id}>{product.product_code} · {product.name}</option>)}</select><select name="direction" defaultValue="increase" className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm"><option value="increase">Increase</option><option value="decrease">Decrease</option></select><input name="quantity" type="number" min="1" required placeholder="Quantity" className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm" /><textarea name="reason" required placeholder="Reason" className="min-h-24 rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm sm:col-span-2" /></div>{adjustState.error ? <p role="alert" className="mt-4 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{adjustState.error}</p> : null}{adjustState.success ? <p role="status" className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{adjustState.success}</p> : null}<button type="submit" disabled={adjustPending} className="mt-5 h-11 w-full rounded-xl bg-slate-900 text-sm font-semibold text-white hover:bg-slate-800 disabled:bg-slate-300">{adjustPending ? "Saving…" : "Save adjustment"}</button></form>
  </div>;
}
