import { StatCard } from "@/components/stat-card";
import { getCurrentProfile, getDashboardSummary } from "@/lib/data";

export const dynamic = "force-dynamic";

export default async function DashboardPage() {
  const profile = await getCurrentProfile();
  const summary = await getDashboardSummary(profile);
  const isStaff = profile?.role === "staff";
  const todayLabel = new Intl.DateTimeFormat("en-MY", { dateStyle: "full", timeZone: process.env.BUSINESS_TIMEZONE ?? "Asia/Kuala_Lumpur" }).format(new Date());
  const chartMax = Math.max(...summary.dailyRevenue, 1);

  return (
    <div className="min-h-screen px-4 py-5 sm:px-6 lg:px-10 lg:py-8">
      <header className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-blue-700">{todayLabel}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">Good morning, {profile?.name ?? "Alice"}</h1><p className="mt-2 text-sm text-slate-500">Here&apos;s today&apos;s tuck shop overview.</p></div><a href="/sales" className="inline-flex h-11 items-center justify-center rounded-xl bg-blue-700 px-5 text-sm font-semibold text-white shadow-lg shadow-blue-700/20 transition hover:bg-blue-800">+ Record sale</a></header>

      <section aria-label="Key metrics" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{isStaff ? <><StatCard label="My orders today" value={String(summary.myTodayOrders)} detail="Orders recorded by you" tone="blue" /><StatCard label="Active products" value={String(summary.activeProductCount)} detail="Available to sell" tone="violet" /><StatCard label="Low-stock products" value={String(summary.lowStockProducts.length)} detail="Check inventory before selling" tone="amber" /><StatCard label="Quick action" value="+" detail="Record a sale" tone="emerald" /></> : <><StatCard label="Today&apos;s revenue" value={`RM${summary.todayRevenue.toFixed(2)}`} detail={`${summary.todayOrders} valid orders`} tone="blue" /><StatCard label="Monthly revenue" value={`RM${summary.monthRevenue.toFixed(2)}`} detail="Completed sales this month" tone="violet" /><StatCard label="Monthly profit" value={`RM${summary.monthProfit.toFixed(2)}`} detail="Historical sale costs" tone="emerald" /><StatCard label="Today&apos;s orders" value={String(summary.todayOrders)} detail="Voided sales excluded" tone="amber" /></>}</section>

      <section className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]">{isStaff ? <div className="rounded-3xl border border-blue-100 bg-blue-50 p-6"><h2 className="font-semibold text-blue-950">Ready for the next order?</h2><p className="mt-2 max-w-md text-sm leading-6 text-blue-800">Search active products, add quantities, and save the sale. The server checks stock before it commits.</p><a href="/sales" className="mt-6 inline-flex h-11 items-center rounded-xl bg-blue-700 px-5 text-sm font-semibold text-white hover:bg-blue-800">Record a sale →</a></div> : <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-slate-950">Revenue trend</h2><p className="mt-1 text-sm text-slate-500">Last 14 business days</p></div><span className="rounded-lg bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-500">Live data</span></div><div className="mt-8 flex h-52 items-end gap-2 sm:gap-3" aria-label="Revenue chart"><span className="sr-only">Daily revenue bars for the last 14 days</span>{summary.dailyRevenue.map((revenue, index) => <div key={`${index}-${revenue}`} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-lg bg-blue-600" style={{ height: `${Math.max(8, (revenue / chartMax) * 100)}%` }} title={`RM${revenue.toFixed(2)}`} /><span className="text-[10px] text-slate-400">{index + 1}</span></div>)}</div></div>}

        <div className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold text-amber-950">Low stock alert</h2><p className="mt-1 text-sm text-amber-800">{summary.lowStockProducts.length} products need attention.</p></div><span className="grid size-10 place-items-center rounded-2xl bg-white text-xl text-amber-600 shadow-sm">!</span></div>{summary.lowStockProducts.length === 0 ? <p className="mt-6 text-sm text-amber-800">All active products are above their minimum stock.</p> : <ul className="mt-6 divide-y divide-amber-200/70">{summary.lowStockProducts.map((product) => <li key={product.name} className="flex items-center justify-between py-3 text-sm"><span className="font-medium text-amber-950">{product.name}</span><span className="font-semibold text-amber-700">{product.currentStock} left</span></li>)}</ul>}<a href="/inventory" className="mt-4 inline-block text-sm font-semibold text-amber-900 underline decoration-amber-300 underline-offset-4">View inventory</a></div>
      </section>

      {!isStaff ? <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="font-semibold text-slate-950">Best-selling products</h2><p className="mt-1 text-sm text-slate-500">Top products this month</p></div><a href="/reports" className="self-start text-sm font-semibold text-blue-700 hover:text-blue-800 sm:self-auto">View report →</a></div>{summary.bestSelling.length === 0 ? <p className="mt-6 text-sm text-slate-500">No completed sales this month.</p> : <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead className="border-b border-slate-100 text-xs uppercase tracking-wider text-slate-400"><tr><th className="pb-3 font-semibold">Product</th><th className="pb-3 font-semibold">Units sold</th><th className="pb-3 text-right font-semibold">Revenue</th></tr></thead><tbody className="divide-y divide-slate-100">{summary.bestSelling.map((product, index) => <tr key={product.name}><td className="py-4 font-medium text-slate-800"><span className={`mr-3 inline-block size-2 rounded-full ${index % 3 === 0 ? "bg-blue-600" : index % 3 === 1 ? "bg-rose-500" : "bg-amber-500"}`} />{product.name}</td><td className="py-4 text-slate-500">{product.sold}</td><td className="py-4 text-right font-semibold text-slate-800">RM{product.revenue.toFixed(2)}</td></tr>)}</tbody></table></div>}</section> : null}
    </div>
  );
}
