-- Approved catalogue mapping (unknown name_en/barcode intentionally remain NULL).
do $$
declare mapped_count integer;
begin
  with mapping(product_code, name_zh, brand, flavour, size, package_type, category) as (values
    ('HK-001','礦泉水','Cool',null,'750ml',null,'飲品'),('HK-002','媽咪麵',null,null,null,null,'即食麵'),
    ('HK-003','QQ糖','旺仔','藍莓','',null,'糖果'),('HK-004','QQ糖','旺仔','蜜桃','',null,'糖果'),('HK-005','QQ糖','旺仔','葡萄','',null,'糖果'),
    ('HK-006','薯片','卡樂B','燒烤','25g',null,'薯片／脆片'),('HK-007','薯片','卡樂B','番茄','55g',null,'薯片／脆片'),('HK-008','薯片','卡樂B','熱浪','25g',null,'薯片／脆片'),
    ('HK-009','魷魚絲','大發',null,'30g',null,'肉類零食'),('HK-010','紫菜','小老闆','原味',null,'袋裝','紫菜'),('HK-011','紫菜','小老闆','原味',null,'片裝','紫菜'),('HK-012','紫菜','小老闆','辣味',null,'片裝','紫菜'),
    ('HK-013','特濃牛奶','旺仔',null,'125ml',null,'乳製品'),('HK-014',null,'維他奶',null,'250ml',null,'飲品'),('HK-015','麥精','維他','', '250ml',null,'飲品'),('HK-016','蘋果綠茶',null,null,'250ml',null,'飲品'),('HK-017','清涼爽',null,null,'300ml',null,'飲品'),
    ('HK-018','菊花烏龍茶','地道',null,'250ml',null,'飲品'),('HK-019','解茶','地道',null,'250ml',null,'飲品'),('HK-020','茉莉綠茶','地道',null,'250ml',null,'飲品'),('HK-021','檸檬茶',null,null,'250ml',null,'飲品'),('HK-022','白提子汁','Qoo',null,null,null,'飲品'),('HK-023','荔枝玉露',null,null,null,'罐裝','飲品'),
    ('HK-024','抽紙','維達','綠茶香',null,null,'紙品／日用品'),('HK-025','抽紙','維達','爽身粉香',null,null,'紙品／日用品'),('HK-026','啫喱',null,'雜果',null,null,'啫喱'),('HK-027','小小酥','旺旺','香蔥雞',null,null,'餅乾'),('HK-028','小小酥','旺旺','原味',null,null,'餅乾'),('HK-029','美味棒',null,'忌廉湯',null,null,'餅乾'),('HK-030','奶片',null,null,null,null,'乳製品'),('HK-031','可樂橡皮糖',null,null,null,null,'糖果'),
    ('HK-032','動物餅',null,null,null,'袋裝','餅乾'),('HK-033','魚仔餅',null,'紫菜',null,null,'餅乾'),('HK-034','魚仔餅',null,'燒雞',null,null,'餅乾'),('HK-035','熊仔餅',null,'朱古力',null,null,'餅乾'),('HK-036','熊仔餅',null,'士多啤梨',null,null,'餅乾'),('HK-037','小饅頭','旺仔',null,null,null,'餅乾'),('HK-038','黑白配',null,null,null,null,'餅乾'),('HK-039','仙貝','旺旺',null,null,null,'餅乾'),('HK-040','燒餅','旺旺',null,null,null,'餅乾'),
    ('HK-041','百力滋',null,'抹茶',null,null,'餅乾'),('HK-042','百力滋',null,'番茄',null,null,'餅乾'),('HK-043','百力滋',null,'朱古力曲奇',null,null,'餅乾'),('HK-044','鵪鶉蛋',null,'鹽焗',null,null,'肉類零食'),('HK-045','鵪鶉蛋',null,'香辣',null,null,'肉類零食'),('HK-046','魷魚絲',null,'勁辣',null,null,'肉類零食'),('HK-047','腸仔',null,null,null,null,'肉類零食'),('HK-048','一口芝士條',null,null,null,null,'乳製品'),('HK-049','蒜香青豆',null,null,null,null,'堅果／豆類'),('HK-050','脆皮花生',null,null,null,null,'堅果／豆類'),('HK-051','醬油','牛角',null,null,null,'調味／食品配料'),('HK-052','飯素','牛角',null,null,null,'調味／食品配料'),('HK-053','甜筒蛋糕',null,null,null,null,'餅乾'),('HK-054','薯片','卡樂B','雜菜',null,'掛裝','薯片／脆片'),('HK-055','辛拉麵',null,null,null,null,'即食麵'),('HK-056','炒麵王',null,'香辣',null,null,'即食麵'),('HK-057','戒指糖',null,'雜',null,null,'糖果')
  ) select count(*) into mapped_count from mapping;
  if mapped_count <> 57 then raise exception 'Catalogue mapping must contain 57 rows'; end if;
end $$;

with mapping(product_code, name_zh, brand, flavour, size, package_type, category) as (values
  ('HK-001','礦泉水','Cool',null,'750ml',null,'飲品'),('HK-002','媽咪麵',null,null,null,null,'即食麵'),('HK-003','QQ糖','旺仔','藍莓',null,null,'糖果'),('HK-004','QQ糖','旺仔','蜜桃',null,null,'糖果'),('HK-005','QQ糖','旺仔','葡萄',null,null,'糖果'),('HK-006','薯片','卡樂B','燒烤','25g',null,'薯片／脆片'),('HK-007','薯片','卡樂B','番茄','55g',null,'薯片／脆片'),('HK-008','薯片','卡樂B','熱浪','25g',null,'薯片／脆片'),('HK-009','魷魚絲','大發',null,'30g',null,'肉類零食'),('HK-010','紫菜','小老闆','原味',null,'袋裝','紫菜'),('HK-011','紫菜','小老闆','原味',null,'片裝','紫菜'),('HK-012','紫菜','小老闆','辣味',null,'片裝','紫菜'),('HK-013','特濃牛奶','旺仔',null,'125ml',null,'乳製品'),('HK-014',null,'維他奶',null,'250ml',null,'飲品'),('HK-015','麥精','維他',null,'250ml',null,'飲品'),('HK-016','蘋果綠茶',null,null,'250ml',null,'飲品'),('HK-017','清涼爽',null,null,'300ml',null,'飲品'),('HK-018','菊花烏龍茶','地道',null,'250ml',null,'飲品'),('HK-019','解茶','地道',null,'250ml',null,'飲品'),('HK-020','茉莉綠茶','地道',null,'250ml',null,'飲品'),('HK-021','檸檬茶',null,null,'250ml',null,'飲品'),('HK-022','白提子汁','Qoo',null,null,null,'飲品'),('HK-023','荔枝玉露',null,null,null,'罐裝','飲品'),('HK-024','抽紙','維達','綠茶香',null,null,'紙品／日用品'),('HK-025','抽紙','維達','爽身粉香',null,null,'紙品／日用品'),('HK-026','啫喱',null,'雜果',null,null,'啫喱'),('HK-027','小小酥','旺旺','香蔥雞',null,null,'餅乾'),('HK-028','小小酥','旺旺','原味',null,null,'餅乾'),('HK-029','美味棒',null,'忌廉湯',null,null,'餅乾'),('HK-030','奶片',null,null,null,null,'乳製品'),('HK-031','可樂橡皮糖',null,null,null,null,'糖果'),('HK-032','動物餅',null,null,null,'袋裝','餅乾'),('HK-033','魚仔餅',null,'紫菜',null,null,'餅乾'),('HK-034','魚仔餅',null,'燒雞',null,null,'餅乾'),('HK-035','熊仔餅',null,'朱古力',null,null,'餅乾'),('HK-036','熊仔餅',null,'士多啤梨',null,null,'餅乾'),('HK-037','小饅頭','旺仔',null,null,null,'餅乾'),('HK-038','黑白配',null,null,null,null,'餅乾'),('HK-039','仙貝','旺旺',null,null,null,'餅乾'),('HK-040','燒餅','旺旺',null,null,null,'餅乾'),('HK-041','百力滋',null,'抹茶',null,null,'餅乾'),('HK-042','百力滋',null,'番茄',null,null,'餅乾'),('HK-043','百力滋',null,'朱古力曲奇',null,null,'餅乾'),('HK-044','鵪鶉蛋',null,'鹽焗',null,null,'肉類零食'),('HK-045','鵪鶉蛋',null,'香辣',null,null,'肉類零食'),('HK-046','魷魚絲',null,'勁辣',null,null,'肉類零食'),('HK-047','腸仔',null,null,null,null,'肉類零食'),('HK-048','一口芝士條',null,null,null,null,'乳製品'),('HK-049','蒜香青豆',null,null,null,null,'堅果／豆類'),('HK-050','脆皮花生',null,null,null,null,'堅果／豆類'),('HK-051','醬油','牛角',null,null,null,'調味／食品配料'),('HK-052','飯素','牛角',null,null,null,'調味／食品配料'),('HK-053','甜筒蛋糕',null,null,null,null,'餅乾'),('HK-054','薯片','卡樂B','雜菜',null,'掛裝','薯片／脆片'),('HK-055','辛拉麵',null,null,null,null,'即食麵'),('HK-056','炒麵王',null,'香辣',null,null,'即食麵'),('HK-057','戒指糖',null,'雜',null,null,'糖果')
)
update public.products p set name_zh=m.name_zh,name_en=null,brand=m.brand,flavour=m.flavour,size=m.size,package_type=m.package_type,barcode=null,category=m.category
from mapping m where lower(p.product_code)=lower(m.product_code);

do $$ begin
  if (select count(*) from public.products where product_code ~ '^HK-[0-9]{3}$' and cast(right(product_code, 3) as integer) between 1 and 57) <> 57 then raise exception 'Expected all HK-001..HK-057 catalogue products'; end if;
  if (select count(distinct product_code) from public.products where product_code ~ '^HK-[0-9]{3}$' and cast(right(product_code, 3) as integer) between 1 and 57) <> 57 then raise exception 'HK catalogue codes must be unique'; end if;
end $$;
